# JVM
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Build no transitiva de R class (mejor rendimiento)
android.nonTransitiveRClass=true

# Configuración en paralelo y caché
org.gradle.parallel=true
org.gradle.caching=true
